### ISSUE TITLE
Suggestion: option to use href="#" if the image is the same...

### ISSUE THREAD

**Issue by ghost** [vaughnroyko/lightLightBox#2]
Added the ability to use # as href and grab image path from the main image.
```
imgURL = $( this ).find( 'img' ).attr( 'src' );
```

to

```
if ($( this ).attr('href') == '#') {
    imgURL = $( this ).find( 'img' ).attr( 'src' );
} else {
    imgURL = $( this ).attr( 'href' );
}  
```

Thank you for the solution. It was exactly what I wanted. Simple. One file.

**Comment by vaughnroyko** [comment]
Thanks for the suggestion. I have added in this functionality in the latest release.
